"""initial schema

Revision ID: 610d79b661fa
Revises: 
Create Date: 2026-09-12 12:01:05.096386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610d79b661fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('asset_criticality',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('age_years', sa.Float(), nullable=True),
    sa.Column('historical_failure_count', sa.Integer(), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('asset_id_mappings',
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_asset_id', sa.String(), nullable=False),
    sa.Column('canonical_asset_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('source_system', 'source_asset_id')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('block_plans',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('corridor_id_mappings',
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_corridor_id', sa.String(), nullable=False),
    sa.Column('canonical_corridor_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('source_system', 'source_corridor_id')
    )
    op.create_table('corridor_slots',
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('corridor_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('derived_from', sa.String(), nullable=True),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('freight_forecast_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corridor_id', sa.String(), nullable=False),
    sa.Column('forecast_window_start', sa.DateTime(), nullable=False),
    sa.Column('forecast_window_end', sa.DateTime(), nullable=False),
    sa.Column('expected_goods_traffic', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_batches',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('rows_in', sa.Integer(), nullable=True),
    sa.Column('rows_valid', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('rows_review', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('maintenance_tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('defect_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('overdue_days', sa.Integer(), nullable=False),
    sa.Column('required_duration_hours', sa.Float(), nullable=False),
    sa.Column('corridor_id', sa.String(), nullable=False),
    sa.Column('safety_critical', sa.Boolean(), nullable=True),
    sa.Column('interlocking_critical', sa.Boolean(), nullable=True),
    sa.Column('mutually_exclusive_with', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('unscheduled_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('ml_model_runs',
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('trained_on', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('feature_importance_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('raw_row_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('scoring_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('stations',
    sa.Column('station_code', sa.String(), nullable=False),
    sa.Column('station_name', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('station_code')
    )
    op.create_table('task_predictions',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('failure_risk_probability', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('criticality_score', sa.Float(), nullable=True),
    sa.Column('ml_priority_score', sa.Float(), nullable=True),
    sa.Column('shap_explanation', sa.Text(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('train_timetable_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.String(), nullable=False),
    sa.Column('train_name', sa.String(), nullable=True),
    sa.Column('from_station_code', sa.String(), nullable=False),
    sa.Column('to_station_code', sa.String(), nullable=False),
    sa.Column('corridor_id', sa.String(), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('block_plan_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('corridor_id', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('assigned_window_start', sa.DateTime(), nullable=False),
    sa.Column('assigned_window_end', sa.DateTime(), nullable=False),
    sa.Column('co_scheduled_departments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['block_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_plan_entries')
    op.drop_table('users')
    op.drop_table('train_timetable_entries')
    op.drop_table('task_predictions')
    op.drop_table('stations')
    op.drop_table('scoring_config')
    op.drop_table('revoked_tokens')
    op.drop_table('review_queue')
    op.drop_table('ml_model_runs')
    op.drop_table('maintenance_tasks')
    op.drop_table('ingestion_batches')
    op.drop_table('freight_forecast_entries')
    op.drop_table('corridor_slots')
    op.drop_table('corridor_id_mappings')
    op.drop_table('block_plans')
    op.drop_table('audit_log')
    op.drop_table('asset_id_mappings')
    op.drop_table('asset_criticality')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
