"""add weather-aware scheduling tables

Revision ID: 7cf00cd1694f
Revises: 817e05da8877
Create Date: 2026-09-12 18:39:13.884890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf00cd1694f'
down_revision: Union[str, Sequence[str], None] = '817e05da8877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_weather_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('corridor_id', sa.String(), nullable=True),
    sa.Column('slot_id', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('base_duration_hours', sa.Float(), nullable=True),
    sa.Column('effective_duration_hours', sa.Float(), nullable=True),
    sa.Column('buffer_pct_applied', sa.Float(), nullable=True),
    sa.Column('hazard', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('forecast_precipitation_pct', sa.Float(), nullable=True),
    sa.Column('forecast_wind_kmh', sa.Float(), nullable=True),
    sa.Column('forecast_temp_max_c', sa.Float(), nullable=True),
    sa.Column('forecast_lightning_risk', sa.Boolean(), nullable=True),
    sa.Column('forecast_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecast_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corridor_id', sa.String(), nullable=False),
    sa.Column('station_code', sa.String(), nullable=True),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('precipitation_probability_pct', sa.Float(), nullable=False),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=False),
    sa.Column('visibility_km', sa.Float(), nullable=True),
    sa.Column('fog_risk', sa.Boolean(), nullable=True),
    sa.Column('lightning_risk', sa.Boolean(), nullable=True),
    sa.Column('temperature_max_c', sa.Float(), nullable=False),
    sa.Column('temperature_min_c', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_sensitivity_rules',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('defect_type_pattern', sa.String(), nullable=False),
    sa.Column('hazard', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('duration_buffer_pct', sa.Float(), nullable=True),
    sa.Column('priority_points', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_sensitivity_rules')
    op.drop_table('weather_forecast_entries')
    op.drop_table('task_weather_assessments')
    # ### end Alembic commands ###
