"""add station coordinates

Revision ID: 817e05da8877
Revises: 610d79b661fa
Create Date: 2026-09-12 12:26:55.651005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817e05da8877'
down_revision: Union[str, Sequence[str], None] = '610d79b661fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('stations', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'lon')
    op.drop_column('stations', 'lat')
    # ### end Alembic commands ###
