"""manual override (FR-COA-03): block_plan_entries/block_plans override
columns, override_requests table

Revision ID: a1b2c3d4e5f6
Revises: f52ccd6cb56a
Create Date: 2026-09-13 06:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'f52ccd6cb56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_plan_entries', sa.Column('override', sa.Boolean(), nullable=True))
    op.add_column('block_plan_entries', sa.Column('override_reason', sa.Text(), nullable=True))
    op.add_column('block_plan_entries', sa.Column('override_by', sa.String(), nullable=True))
    op.add_column('block_plan_entries', sa.Column('override_at', sa.DateTime(), nullable=True))
    op.add_column('block_plans', sa.Column('modified_after_publication', sa.Boolean(), nullable=True))
    op.create_table('override_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('override_requests')
    op.drop_column('block_plans', 'modified_after_publication')
    op.drop_column('block_plan_entries', 'override_at')
    op.drop_column('block_plan_entries', 'override_by')
    op.drop_column('block_plan_entries', 'override_reason')
    op.drop_column('block_plan_entries', 'override')
    # ### end Alembic commands ###
