"""real station master, corridor entity, vacancy provenance, hourly weather

Revision ID: f52ccd6cb56a
Revises: 391450a62cd3
Create Date: 2026-09-13 00:31:50.559032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52ccd6cb56a'
down_revision: Union[str, Sequence[str], None] = '391450a62cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corridors',
    sa.Column('corridor_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('from_station_code', sa.String(), nullable=False),
    sa.Column('to_station_code', sa.String(), nullable=False),
    sa.Column('intermediate_stations', sa.Text(), nullable=True),
    sa.Column('section_ids', sa.Text(), nullable=True),
    sa.Column('section_count', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('geometry_json', sa.Text(), nullable=True),
    sa.Column('train_count', sa.Integer(), nullable=True),
    sa.Column('derived_from', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('corridor_id')
    )
    op.create_table('weather_hourly_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corridor_id', sa.String(), nullable=False),
    sa.Column('valid_time', sa.DateTime(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('precipitation_probability_pct', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('visibility_km', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('lightning_risk', sa.Boolean(), nullable=True),
    sa.Column('fog_risk', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('corridor_slots', sa.Column('train_before_id', sa.String(), nullable=True))
    op.add_column('corridor_slots', sa.Column('train_after_id', sa.String(), nullable=True))
    op.add_column('corridor_slots', sa.Column('buffer_minutes', sa.Integer(), nullable=True))
    op.add_column('corridor_slots', sa.Column('sections_considered', sa.Integer(), nullable=True))
    op.add_column('stations', sa.Column('station_name_hindi', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('state', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('division', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('address', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('elevation_m', sa.Float(), nullable=True))
    op.add_column('stations', sa.Column('station_type', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('source', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'updated_at')
    op.drop_column('stations', 'source')
    op.drop_column('stations', 'station_type')
    op.drop_column('stations', 'elevation_m')
    op.drop_column('stations', 'address')
    op.drop_column('stations', 'division')
    op.drop_column('stations', 'state')
    op.drop_column('stations', 'station_name_hindi')
    op.drop_column('corridor_slots', 'sections_considered')
    op.drop_column('corridor_slots', 'buffer_minutes')
    op.drop_column('corridor_slots', 'train_after_id')
    op.drop_column('corridor_slots', 'train_before_id')
    op.drop_table('weather_hourly_forecasts')
    op.drop_table('corridors')
    # ### end Alembic commands ###
